#Raspberry Pi | Home Media Server

version: "3.9"

services:
  deluge:
    container_name: deluge
    image: ghcr.io/linuxserver/deluge
    restart: always
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - DELUGE_LOGLEVEL=error #optional
    volumes:
      - ${ROOT}/downloads:/downloads
      - ${ROOT}/config/deluge:/config
    ports:
      - 8112:8112
      - 6881:6881
      - 6881:6881/udp

  jackett:
    container_name: jackett
    image: ghcr.io/linuxserver/jackett
    restart: always
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - AUTO_UPDATE=true
      - RUN_OPTS=<run options here>
    volumes:
      - ${ROOT}/downloads/torrent-blackhole:/downloads
      - ${ROOT}/config/jackett:/config
    ports:
      - 9117:9117

  nzbget:
    container_name: nzbget
    image: ghcr.io/linuxserver/nzbget:latest
    restart: always
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${ROOT}/downloads:/downloads
      - ${ROOT}/config/nzbget:/config

  radarr:
    container_name: radarr
    image: ghcr.io/linuxserver/radarr
    restart: always
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${ROOT}/config/radarr:/config
      - ${ROOT}/complete/movies:/movies
      - ${ROOT}/downloads:/downloads
    ports:
      - 7878:7878

  sonarr:
    container_name: sonarr
    image: ghcr.io/linuxserver/sonarr
    restart: always
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${ROOT}/config/sonarr:/config
      - ${ROOT}/complete/tv:/tv
      - ${ROOT}/downloads:/downloads
    ports:
      - 8989:8989

  plex-server:
    container_name: plex-server
    image: ghcr.io/linuxserver/plex
    restart: always
    environment:
      - TZ=${TZ}
    network_mode: host
    volumes:
      - ${ROOT}/config/plex/db:/config
      - ${ROOT}/config/plex/transcode:/transcode
      - ${ROOT}/complete:/data
